export enum ColumnSize {
  isFull = 'is-full',
  isOneQuarter = 'is-one-quarter',
  isOneThird = 'is-one-third',
  isHalf = 'is-half',
  isTwoThirds = 'is-two-thirds',
  isThreeQuarters = 'is-three-quarters',
  isFourFifths = 'is-four-fifths',
  isThreeFifths = 'is-three-fifths',
  isTwoFifths = 'is-two-fifths',
  isOneFifth = 'is-one-fifth',
  is1 = 'is-1',
  is2 = 'is-2',
  is3 = 'is-3',
  is4 = 'is-4',
  is5 = 'is-5',
  is6 = 'is-6',
  is7 = 'is-7',
  is8 = 'is-8',
  is9 = 'is-9',
  is10 = 'is-10',
  is11 = 'is-11',
  is12 = 'is-12',
}

export enum IsNarrow {
  Mobile = 'is-narrow-mobile',
  Tablet = 'is-narrow-tablet',
  Touch = 'is-narrow-touch',
  Desktop = 'is-narrow-desktop',
  Widescreen = 'is-narrow-widescreen',
  Fullhd = 'is-narrow-fullhd',
}
